name: Build Kernel

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Properties # Output will be use in final name of recovery.
      id: props
      run: |
        echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      
    - name: Start Building Kernel
      run: |
        ./build

    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
        artifacts: /home/runner/work/ANY/*.zip
        name: Action-Kernel-Builder Release
        draft: false
        prerelease: false
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Action-Kernel-Builder: ${{ steps.props.outputs.date }}
          Note:
            - Do not flash the .zip, this includes all files in out/boot folder.
            - Some kernel build has different name (Image, Image.gz-dtb) so instead of compressing only the kernel itself as flashable, this builder compressed the whole boot/ folder.
            - Find your Kernel in boot/ folder inside the .zip file.
          Flash:
            - Clone [AnyKernel](https://github.com/thecatvoid/AnyKernel3.git)
            - Copy the kernel inside boot/ folder, paste it in AnyKernel3 clone and .zip it.
            - Flash it via twrp or magisk.

    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
