name: Build Kernel

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Properties # Output will be use in final name of recovery.
      id: props
      run: |
        echo "date=$(TZ=Asia/Manila date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
      
    - name: Start Building Kernel
      run: |
        ./build

    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
        artifacts: |
          /home/runner/work/ANY/*.zip
          /home/runner/work/your-kernel/out/arch/arm64/boot/*.zip
        name: Action-Kernel-Builder Release
        draft: false
        prerelease: true
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Action-Kernel-Builder: ${{ steps.props.outputs.date }}
          - Notes:
            - Uploaded AnyKernel3.zip (without kernel inside) and your-kernel-here-xxxxxx.zip with your newly-compiled kernel inside.
            - Read my instruction below first.
          - Flash:
            - Download AnyKernel3.zip and your-kernel-here-xxxxxxx.zip (whatever the name was), extract both.
            - Copy a kernel (could be Image, Image-dtb, Image.gz-dtb, pick one) inside your-kernel-here-xxxxxxx folder, and paste it in AnyKernel3 folder and compressed it.
            - Flash it via twrp or magisk.

    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
